name: Build and Test -> Compute coverage -> Release if requested

on:
  push:
    branches:
      - master
    paths:
      - "src/main/**.java"
      - "src/test/**.java"
      - ".github/workflows/**"
      - "**.properties"
      - "**.xml"

jobs:
    
  build-and-test-with-Java-8-and-later:
    name: Build -> Test (JVM ${{ matrix.java }}, ${{ matrix.os }})
    strategy:
      fail-fast: true
      max-parallel: 16
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [8, 9.0.4, 10, 11, 12, 13, 14, 15, 16, 17, 18]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
      - name: Build and test
        run: mvn -B clean test -Dproject_jdk_version=${{ matrix.java }} -DskipTests=false --file pom.xml
        
  release:
    name: Release if requested
    needs: [build-and-test-with-Java-8-and-later]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && endsWith(github.event.head_commit.message, 'Releasing new version')
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to the Maven Central repository
        run: |
          export GPG_TTY=$(tty)
          echo "${{ secrets.gpg_private_key }}" | gpg --batch --import
          git config user.name "${{ github.event.head_commit.committer.name }}"
          git config user.email "${{ github.event.head_commit.committer.email }}"
          mvn -B release:prepare release:perform -Dproject_jdk_version=8 -DskipTests=true -Dgpg.passphrase=${{ secrets.gpg_passphrase }} -Dgpg.keyname=${{ secrets.gpg_key_id }} -Drepository.url=https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        env:
          MAVEN_USERNAME: ${{ secrets.nexus_username }}
          MAVEN_PASSWORD: ${{ secrets.nexus_password }}
